
# snakemake execution format:
# input: script + other input files
# output: log + other output files
# conda: env name, being activated before running the script.
#   Conda path should be  exported in shell (bashrc) i.e export PATH=/my/path/miniconda/bin:$PATH
#   create conda envs with yaml files in the repo
# params: other parameters, like output dir
# shell: create dir and run script with input and output files, redirect stdout and stderr to log file
# if --profile profiles/slurm is used, it will sbatch the job automatically,
#   otherwise it will run locally

# each dataset has its own  dir, where all input, output, logs, scripts etc are stored
# each dataset has its own Snakefile, which includes this main Snakefile
ensembl_113_star_index = "/sci/data/reference_data/Homo_sapiens/Ensembl/GRCh38/Sequence/STARIndex/Ens113/"
configfile: "workflow/config.yaml"


module enhancers_to_count:
    snakefile: "enhancers_to_count.smk"
    config: config
use rule * from enhancers_to_count as enhancers_*


module PBMC_10X:
    snakefile: "PBMC_10X.smk"
    config: config
use rule * from PBMC_10X as PBMC_10X_*





module test2:
    snakefile: "test2.smk"
    config: config

use rule * from test2 as test2_*