
# snakemake execution format:
# input: script + other input files
# output: log + other output files
# conda: env name, being activated before running the script.
#   Conda path should be  exported in shell (bashrc) i.e export PATH=/my/path/miniconda/bin:$PATH
#   create conda envs with yaml files in the repo
# params: other parameters, like output dir
# shell: create dir and run script with input and output files, redirect stdout and stderr to log file
# if --profile profiles/slurm is used, it will sbatch the job automatically,
#   otherwise it will run locally

# each dataset has its own  dir, where all input, output, logs, scripts etc are stored
# each dataset has its own Snakefile, which includes this main Snakefile
ensembl_113_star_index = "/sci/data/reference_data/Homo_sapiens/Ensembl/GRCh38/Sequence/STARIndex/Ens113/"


module snare:
    snakefile: "snare.smk"

use rule * from snare 

module snare_bwa:
    snakefile: "snare_bwa.smk"

use rule * from snare_bwa as snare_bwa_*

module snare_count_by_atac:
    snakefile: "snare_count_by_atac.smk"

use rule * from snare_count_by_atac as snare_count_by_atac_*

module PBMC_10X_RNA:
    snakefile: "PBMC_10X_RNA.smk"
use rule * from PBMC_10X_RNA as PBMC_10X_RNA_*

module PBMC_10X_ATAC:
    snakefile: "PBMC_10X_ATAC.smk"
use rule * from PBMC_10X_ATAC as PBMC_10X_ATAC_*

module PBMC_10X_analysis:
    snakefile: "PBMC_10X_analysis.smk"
use rule * from PBMC_10X_analysis as PBMC_10X_analysis_*

module test:
    snakefile: "test.smk"


use rule * from test as test_*

module test2:
    snakefile: "test2.smk"


use rule * from test2 as test2_*