
# snakemake execution format:
# input: script + other input files
# output: log + other output files
# conda: env name, being activated before running the script.
#   Conda path should be  exported in shell (bashrc) i.e export PATH=/my/path/miniconda/bin:$PATH
#   create conda envs with yaml files in the repo
# params: other parameters, like output dir
# shell: create dir and run script with input and output files, redirect stdout and stderr to log file
# if --profile profiles/slurm is used, it will sbatch the job automatically,
#   otherwise it will run locally

# each dataset has its own  dir, where all input, output, logs, scripts etc are stored
# each dataset has its own Snakefile, which includes this main Snakefile


module snare:
    snakefile: "snare.smk"

use rule * from snare 



rule test:
    input:
        script = "./test/test.sh"
    output:
        log = "test_log.txt"


    shell:
        '''
        {input.script}  > {output.log} 2>&1
        '''